import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";

import NavBar from "@/components/NavBar/NavBar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Shopping Cart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable,
        )}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
